// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://atzxltedgnbiopefwigz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0enhsdGVkZ25iaW9wZWZ3aWd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg1ODU3NDMsImV4cCI6MjA1NDE2MTc0M30.mZZ6KvX09YBm1JLNg6JLF6LJxSAjGMsqVSpviSHaxuU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);